/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recursoshumanos;

/**
 *
 * @author Zait
 */

public class agregarEmpleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form agregarEmpleado
     */
    
    public agregarEmpleado() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexo = new javax.swing.ButtonGroup();
        turno = new javax.swing.ButtonGroup();
        txtAp = new javax.swing.JTextField();
        txtAm = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        radioMas = new javax.swing.JRadioButton();
        radioFem = new javax.swing.JRadioButton();
        txtNumEmp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jfeNac = new com.toedter.calendar.JDateChooser();
        addBoton = new javax.swing.JButton();
        cancelBoton = new javax.swing.JButton();
        radGeneral = new javax.swing.JRadioButton();
        radRecur = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(136, 200, 246));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Nuevo empleado");
        setToolTipText("");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApActionPerformed(evt);
            }
        });
        getContentPane().add(txtAp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 66, 106, -1));

        txtAm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtAm, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 104, 106, -1));

        txtNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 142, 106, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Apellido paterno");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 69, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Apellido materno");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 107, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Nombre(s)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 145, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Sexo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 186, -1, -1));

        radioMas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioMas.setText("Masculino");
        radioMas.setOpaque(false);
        radioMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMasActionPerformed(evt);
            }
        });
        getContentPane().add(radioMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 182, -1, -1));

        radioFem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioFem.setText("Femenino");
        radioFem.setOpaque(false);
        getContentPane().add(radioFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 182, -1, -1));

        txtNumEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNumEmp.setText("00000");
        txtNumEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumEmpActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 28, 106, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Número de empleado");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 31, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Turno");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 279, -1, -1));

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setText("Matutino");
        jRadioButton1.setOpaque(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 275, -1, -1));

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setText("Vespertino");
        jRadioButton2.setOpaque(false);
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 275, -1, -1));

        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3.setText("Mixto");
        jRadioButton3.setOpaque(false);
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 275, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Fecha de nacimiento");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 229, -1, -1));
        getContentPane().add(jfeNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 161, -1));

        addBoton.setBackground(new java.awt.Color(0, 0, 153));
        addBoton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addBoton.setText("Agregar");
        addBoton.setOpaque(false);
        addBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBotonActionPerformed(evt);
            }
        });
        getContentPane().add(addBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 374, -1, -1));

        cancelBoton.setBackground(new java.awt.Color(255, 51, 0));
        cancelBoton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelBoton.setText("Cancelar");
        cancelBoton.setOpaque(false);
        cancelBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBotonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 374, -1, -1));

        radGeneral.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radGeneral.setText("General");
        radGeneral.setOpaque(false);
        getContentPane().add(radGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 316, -1, -1));

        radRecur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radRecur.setText("Recursos Humanos");
        radRecur.setOpaque(false);
        getContentPane().add(radRecur, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 316, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApActionPerformed

    private void radioMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMasActionPerformed

    private void txtNumEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumEmpActionPerformed
        //Se hace un random para tener el número de empleado
    }//GEN-LAST:event_txtNumEmpActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void addBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBotonActionPerformed

    private void cancelBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBotonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelBotonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBoton;
    private javax.swing.JButton cancelBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private com.toedter.calendar.JDateChooser jfeNac;
    private javax.swing.JRadioButton radGeneral;
    private javax.swing.JRadioButton radRecur;
    private javax.swing.JRadioButton radioFem;
    private javax.swing.JRadioButton radioMas;
    private javax.swing.ButtonGroup sexo;
    private javax.swing.ButtonGroup turno;
    private javax.swing.JTextField txtAm;
    private javax.swing.JTextField txtAp;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNumEmp;
    // End of variables declaration//GEN-END:variables
}
